// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateOrAttachTerminal(arg1, arg2) {
  return window['go']['main']['App']['CreateOrAttachTerminal'](arg1, arg2);
}

export function CreateWorktree(arg1) {
  return window['go']['main']['App']['CreateWorktree'](arg1);
}

export function DeleteWorktree(arg1, arg2) {
  return window['go']['main']['App']['DeleteWorktree'](arg1, arg2);
}

export function DestroyTerminal(arg1) {
  return window['go']['main']['App']['DestroyTerminal'](arg1);
}

export function DetachTerminal(arg1) {
  return window['go']['main']['App']['DetachTerminal'](arg1);
}

export function GetRepoPath() {
  return window['go']['main']['App']['GetRepoPath']();
}

export function GetTerminalState(arg1) {
  return window['go']['main']['App']['GetTerminalState'](arg1);
}

export function GetWorktreeStatus(arg1) {
  return window['go']['main']['App']['GetWorktreeStatus'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HasTmux() {
  return window['go']['main']['App']['HasTmux']();
}

export function ListBranches() {
  return window['go']['main']['App']['ListBranches']();
}

export function ListTerminalSessions() {
  return window['go']['main']['App']['ListTerminalSessions']();
}

export function ListWorktrees() {
  return window['go']['main']['App']['ListWorktrees']();
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function SendTerminalInput(arg1, arg2) {
  return window['go']['main']['App']['SendTerminalInput'](arg1, arg2);
}

export function SetRepoPath(arg1) {
  return window['go']['main']['App']['SetRepoPath'](arg1);
}
