// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {worktree} from '../models';
import {terminal} from '../models';

export function CreateOrAttachTerminal(arg1:string,arg2:string):Promise<void>;

export function CreateWorktree(arg1:worktree.CreateOptions):Promise<worktree.Worktree>;

export function DeleteWorktree(arg1:string,arg2:boolean):Promise<void>;

export function DestroyTerminal(arg1:string):Promise<void>;

export function DetachTerminal(arg1:string):Promise<void>;

export function GetRepoPath():Promise<string>;

export function GetTerminalState(arg1:string):Promise<string>;

export function GetWorktreeStatus(arg1:string):Promise<worktree.WorktreeStatus>;

export function Greet(arg1:string):Promise<string>;

export function HasTmux():Promise<boolean>;

export function ListBranches():Promise<Array<string>>;

export function ListTerminalSessions():Promise<Array<terminal.SessionInfo>>;

export function ListWorktrees():Promise<Array<worktree.Worktree>>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SendTerminalInput(arg1:string,arg2:string):Promise<void>;

export function SetRepoPath(arg1:string):Promise<void>;
